version: '3.9'

services:

  project-app:
    build: .
    ports:
      - "5000:8080"
    links:
      - mongo-database
    depends_on:
      - mongo-database
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
  
  mongo-database:
    image: mongo:latest
    ports:
      - "27020:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data-cont:/data/db


volumes:
  mongodb-data-cont : {}
    
      
    
